In [43]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
preprocessed_data = pd.read_csv('preprocessed_data.csv')
preprocessed_data

,Unnamed: 0,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month value,Weekday,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,695,1,0,0,0,5,2,179,22,40,237.656,22,1,2,0,8
696,696,1,0,0,0,5,2,225,26,28,237.656,24,0,1,2,3
697,697,1,0,0,0,5,3,330,16,28,237.656,25,1,0,0,8
698,698,0,0,0,1,5,3,235,16,32,237.656,25,1,0,0,2
699,699,0,0,0,1,5,3,291,31,40,237.656,25,0,1,1,2

In [5]:
preprocessed_data = preprocessed_data.iloc[:,1:]
preprocessed_data

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month value,Weekday,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,5,2,179,22,40,237.656,22,1,2,0,8
696,1,0,0,0,5,2,225,26,28,237.656,24,0,1,2,3
697,1,0,0,0,5,3,330,16,28,237.656,25,1,0,0,8
698,0,0,0,1,5,3,235,16,32,237.656,25,1,0,0,2
699,0,0,0,1,5,3,291,31,40,237.656,25,0,1,1,2

In [7]:
preprocessed_data['Absenteeism Time in Hours'].unique()

array([  4,   0,   2,   8,  40,   1,   7,   3,  32,   5,  16,  24,  64,
        56,  80, 120, 112, 104,  48], dtype=int64)

In [9]:
preprocessed_data['Absenteeism Time in Hours'].median()

3.0

In [13]:
preprocessed_data['Excessive Absentees'] = np.where(preprocessed_data['Absenteeism Time in Hours'] > preprocessed_data['Absenteeism Time in Hours'].median(),
                                                   1, 0)

In [15]:
preprocessed_data

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month value,Weekday,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive Absentees
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,5,2,179,22,40,237.656,22,1,2,0,8,1
696,1,0,0,0,5,2,225,26,28,237.656,24,0,1,2,3,0
697,1,0,0,0,5,3,330,16,28,237.656,25,1,0,0,8,1
698,0,0,0,1,5,3,235,16,32,237.656,25,1,0,0,2,0
699,0,0,0,1,5,3,291,31,40,237.656,25,0,1,1,2,0

In [17]:
preprocessed_data.drop(['Absenteeism Time in Hours'], axis=1, inplace=True)

In [19]:
preprocessed_data

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month value,Weekday,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Excessive Absentees
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,5,2,179,22,40,237.656,22,1,2,0,1
696,1,0,0,0,5,2,225,26,28,237.656,24,0,1,2,0
697,1,0,0,0,5,3,330,16,28,237.656,25,1,0,0,1
698,0,0,0,1,5,3,235,16,32,237.656,25,1,0,0,0
699,0,0,0,1,5,3,291,31,40,237.656,25,0,1,1,0

In [21]:
preprocessed_data['Excessive Absentees'].sum()

319

In [23]:
targets = pd.DataFrame(preprocessed_data.iloc[:,-1])

In [25]:
preprocessed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   reason_type_1            700 non-null    int64
 1   reason_type_2            700 non-null    int64
 2   reason_type_3            700 non-null    int64
 3   reason_type_4            700 non-null    int64
 4   Month value              700 non-null    int64
 5   Weekday                  700 non-null    int64
 6   Transportation Expense   700 non-null    int64
 7   Distance to Work         700 non-null    int64
 8   Age                      700 non-null    int64
 9   Daily Work Load Average  700 non-null    float64
 10  Body Mass Index          700 non-null    int64
 11  Education                700 non-null    int64
 12  Children                 700 non-null    int64
 13  Pets                     700 non-null    int64
 14  Excessive Absentees      700 non-null    int32
dtypes: float64(1), int32(1), int64(13)
memory usage: 79.4 KB

In [29]:
inputs = pd.DataFrame(preprocessed_data.iloc[:,:-1])

In [27]:
targets

     Excessive Absentees
0                      1
1                      0
2                      0
3                      1
4                      0
..                   ...
695                    1
696                    0
697                    1
698                    0
699                    0

[700 rows x 1 columns]

In [31]:
inputs

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month value,Weekday,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,5,2,179,22,40,237.656,22,1,2,0
696,1,0,0,0,5,2,225,26,28,237.656,24,0,1,2
697,1,0,0,0,5,3,330,16,28,237.656,25,1,0,0
698,0,0,0,1,5,3,235,16,32,237.656,25,1,0,0
699,0,0,0,1,5,3,291,31,40,237.656,25,0,1,1

In [33]:
X_train, X_test, y_train, y_test = train_test_split(inputs, targets, random_state=20)

In [35]:
X_train

,reason_type_1,reason_type_2,reason_type_3,reason_type_4,Month value,Weekday,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
266,0,0,0,1,8,2,118,13,50,265.615,31,0,1,0
424,1,0,0,0,4,2,118,10,37,239.409,28,0,0,0
290,0,0,0,1,10,2,235,11,37,265.017,29,1,1,1
397,0,0,0,1,3,1,378,49,36,244.387,21,0,2,4
398,0,0,0,1,3,0,179,51,38,244.387,31,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,1,0,0,0,5,2,118,13,50,378.884,31,0,1,0
223,0,0,0,1,6,3,291,31,40,377.550,25,0,1,1
271,0,0,0,1,9,4,179,51,38,294.217,31,0,0,0
474,0,0,0,1,7,4,361,52,28,230.290,27,0,1,4
355,0,0,0,1,12,0,157,27,29,236.629,22,0,0,0

In [41]:
y_train

     Excessive Absentees
266                    0
424                    0
290                    1
397                    1
398                    1
..                   ...
218                    1
223                    1
271                    0
474                    1
355                    0

[525 rows x 1 columns]

In [ ]:
525/700

In [45]:
reg1 = LogisticRegression()

In [47]:
reg1.fit(X_train, y_train)

C:\Users\oskha\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\oskha\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [48]:
reg1.score(X_train, y_train)

0.7295238095238096

In [53]:
scaled_data = StandardScaler()
scaled_data.fit(preprocessed_data.iloc[:,:-1])
standardized_data = scaled_data.transform(preprocessed_data.iloc[:,:-1])
standardized_data

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [55]:
standardized_data.shape

(700, 14)

In [57]:
standardized_data[0]

array([-0.57735027, -0.09298136, -0.31448545,  0.82136542,  0.18272635,
       -0.68370352,  1.00584437,  0.41281584, -0.53606239, -0.80633129,
        0.76743118, -0.44798003,  0.88046927,  0.26848661])

In [59]:
X_train, X_test, y_train, y_test = train_test_split(standardized_data, preprocessed_data.iloc[:,-1].values, random_state=20)

In [61]:
X_train

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.01928035,  0.26848661],
       ...,
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  2.8430157 ],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976]])

In [67]:
reg1.fit(X_train, y_train)

LogisticRegression()

In [69]:
reg1.score(X_train, y_train)

0.7828571428571428

In [73]:
reg1.predict(X_train)

array([0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [75]:
reg1.coef_

array([[ 2.0688732 ,  0.34505419,  1.55646235,  1.2805999 ,  0.21520168,
        -0.11986215,  0.74815809, -0.02104139, -0.20502569, -0.00316874,
         0.37564667, -0.19561377,  0.32514599, -0.34431182]])

In [77]:
reg1.intercept_

array([-0.21065531])

In [79]:
reg1.coef_.size

14

In [150]:
# log(odds) = intercept + c1*a1 + c2*a2 + c3*a3 + ..... + c14*a14
reg_analysis = pd.DataFrame(reg1.coef_.T, columns=['Coefficients'])

In [152]:
reg_analysis

    Coefficients
0       2.068873
1       0.345054
2       1.556462
3       1.280600
4       0.215202
5      -0.119862
6       0.748158
7      -0.021041
8      -0.205026
9      -0.003169
10      0.375647
11     -0.195614
12      0.325146
13     -0.344312

In [157]:
reg_analysis['Coefficients']

0     2.068873
1     0.345054
2     1.556462
3     1.280600
4     0.215202
5    -0.119862
6     0.748158
7    -0.021041
8    -0.205026
9    -0.003169
10    0.375647
11   -0.195614
12    0.325146
13   -0.344312
Name: Coefficients, dtype: float64

In [161]:
reg_analysis = pd.concat([pd.DataFrame(preprocessed_data.iloc[:,:-1].columns, columns=['Feature names']), reg_analysis], axis=1)

In [163]:
reg_analysis

              Feature names  Coefficients
0             reason_type_1      2.068873
1             reason_type_2      0.345054
2             reason_type_3      1.556462
3             reason_type_4      1.280600
4               Month value      0.215202
5                   Weekday     -0.119862
6    Transportation Expense      0.748158
7          Distance to Work     -0.021041
8                       Age     -0.205026
9   Daily Work Load Average     -0.003169
10          Body Mass Index      0.375647
11                Education     -0.195614
12                 Children      0.325146
13                     Pets     -0.344312

In [165]:
reg_analysis.sort_values(by=['Coefficients'], ascending=False)

              Feature names  Coefficients
0             reason_type_1      2.068873
2             reason_type_3      1.556462
3             reason_type_4      1.280600
6    Transportation Expense      0.748158
10          Body Mass Index      0.375647
1             reason_type_2      0.345054
12                 Children      0.325146
4               Month value      0.215202
9   Daily Work Load Average     -0.003169
7          Distance to Work     -0.021041
5                   Weekday     -0.119862
11                Education     -0.195614
8                       Age     -0.205026
13                     Pets     -0.344312